// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "fluidApp.h"
UserInterface::UserInterface(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
{ new Fl_Text_Display(155, 30, 120, 30, "My app");
} // Fl_Text_Display* o
{ Fl_Button* o = new Fl_Button(160, 110, 120, 30, "press");
  o->callback((Fl_Callback*)onButtonClick);
} // Fl_Button* o
end();
}
