// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef fluidApp_h
#define fluidApp_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
extern void onButtonClick(Fl_Button*, void*);

class UserInterface : public Fl_Group {
public:
  UserInterface(int X, int Y, int W, int H, const char *L = 0);
};
#endif
